// test-angular/src/app/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {FormGroup, FormBuilder, Validators} from '@angular/forms';
import {Http} from '@angular/http';
import {Router} from '@angular/router';
import {SharedService} from '../shared/shared.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;

  ngOnInit() {
  }

  constructor(public fb: FormBuilder, private router: Router, private http: Http, private ss: SharedService) {
    this.loginForm = this.fb.group({
      email: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

  doLogin(event) {
    console.log(this.loginForm.value);
    this.http.post('/api/user/login', this.loginForm)
      .subscribe(
        error => console.error('could not post because', error));
  }

}

<div class="row margin-top">
  <form class="col s4 offset-s4" method="post" [formGroup]="loginForm" action="api/user/login"
        (ngSubmit)="doLogin($event)" #appForm="ngForm">

    <div class="row">
      <div class="input-field col s12">
        <input formControlName="email" type="email"
               name="email" id="email" class="validate border-bottom" required min="4" max="30">
        <label data-error="wrong" data-success="right" for="email">Email</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <input formControlName="password" type="password" min="4" max="30" name="password" id="password"
               class="validate border-bottom" required>
        <label for="password">{{'USER.PASSWORD' | translate}}</label>
      </div>
    </div>
    <p class="red-text center">{{errorMsg}}</p>
    <div class="col s4 offset-s2">
      <button class="waves-effect waves-light btn #d7ccc8 brown lighten-4" id="loginBtn" type="submit">{{'INFO.LOGIN' | translate}}</button>
    </div>
    <div class="g-signin2" id="signInButton" data-onsuccess="onSignIn"></div>
  </form>
</div>

// adminApp/src/components/common/login.jsx
import React from 'react';
let gapi;
class Login extends React.Component {

  render() {
    return (
      <div className="row margin-top">
        <form method="post" className="col s4 offset-4" action="api/user/login">
          <div className="row">
            <div className="input-field col s12">
              <input type="email" name="email" id="email" className="validate border-bottom" required min="4"
                     max="30"/>
              <label data-error="wrong" data-success="right" htmlFor="email">Email</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <input type="password" min="4" max="30" name="password" id="password"
                     className="validate border-bottom" required/>
              <label htmlFor="password">Password</label>
            </div>
          </div>
          <div className="col s4 offset-s2">
            <button className="waves-effect waves-light btn #d7ccc8 brown lighten-4" id="loginBtn" type="button">Log
              in
            </button>
          </div>
          <div className="g-signin2" id="signInButton"/>
        </form>
      </div>
    );
  }
}

export default Login;
